# Generated by Django 3.1 on 2021-08-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20210825_2109'),
        ('usuario', '0003_auto_20210826_1302'),
    ]

    operations = [
    ]
