# Generated by Django 3.1 on 2021-08-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20210828_1824'),
        ('usuario', '0008_auto_20210830_1108'),
    ]

    operations = [
    ]
