# Generated by Django 3.0 on 2021-08-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_auto_20210823_1707'),
        ('preguntas', '0002_auto_20210823_1511'),
    ]

    operations = [
    ]
