# Generated by Django 3.0 on 2021-08-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_merge_20210824_0123'),
        ('preguntas', '0002_auto_20210822_2004'),
    ]

    operations = [
    ]
