# Generated by Django 3.0 on 2021-08-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0006_preguntasrespondidas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='¿Es esta la respuesta correcta?'),
        ),
    ]
