# Generated by Django 3.0 on 2021-08-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0006_preguntasrespondidas_usuario'),
        ('preguntas', '0002_auto_20210823_0944'),
    ]

    operations = [
    ]
