# Generated by Django 3.0 on 2021-08-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0007_merge_20210825_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='¿Es esta la respuesta correcta?'),
        ),
    ]
