# Generated by Django 3.0 on 2021-08-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_auto_20210825_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='PreguntasRespondidas',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
