# Generated by Django 3.0 on 2021-08-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0007_auto_20210825_1044'),
        ('preguntas', '0008_auto_20210825_1356'),
    ]

    operations = [
    ]
