# Generated by Django 3.0 on 2021-08-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0009_merge_20210825_1527'),
        ('preguntas', '0009_auto_20210825_1549'),
    ]

    operations = [
    ]
